import type { Lead } from "./types";
import { fitScore } from "./utils";

const RAW_LEADS: Omit<Lead, "score">[] = [
  {
    id: "1",
    company: "Schröder Landmaschinen",
    country: "Duitsland",
    employees: 1200,
    revenue: "€100M+",
    sector: "Agri Machinery",
    contactName: "Heiner Schröder",
    contactTitle: "General Manager",
    linkedinUrl: "https://linkedin.com/in/heiner-schroder",
    status: "nieuw",
    batch: "2026-06-12",
    isNew: false,
    notes: "",
    message:
      "Hi Heiner, ik ben Levi van Legacy Scale Models — we rebranden en lanceren twee premium merken: Universal Hobbies en Weise Toys. Met Schröder Gruppe die 43 locaties vertegenwoordigt door heel Europa wil ik graag een samenwerking verkennen: op maat gemaakte schaalmodellen voor showrooms, klantengeschenken en evenementen. We bieden dit aan een select groepje partijen vóór de publieke lancering. Zou je hier open voor staan?",
  },
  {
    id: "2",
    company: "Royal Agrifirm Group",
    country: "Nederland",
    employees: 1900,
    revenue: "€500M+",
    sector: "Agri Trading",
    contactName: "Caroline Lenaerts",
    contactTitle: "Marketing Comm. Manager EMEA",
    linkedinUrl: "https://linkedin.com/in/caroline-lenaerts",
    status: "bekeken",
    batch: "2026-06-12",
    isNew: false,
    notes: "LinkedIn profiel gevonden. Goed moment tijdens Agritechnica.",
    message:
      "Hi Caroline, ik ben Levi van Legacy Scale Models. We breiden uit met twee premium lijnen: Universal Hobbies en Weise Toys. De internationale schaal van Royal Agrifirm maakt jullie een natuurlijke fit voor co-branded schaalmodellen — ideaal voor boerderijrelaties, beurzen en gifting. Vroege partnervoorwaarden beschikbaar.",
  },
  {
    id: "3",
    company: "Zweegers Equipment Group",
    country: "Nederland",
    employees: 500,
    revenue: "€393M",
    sector: "Agri Machinery",
    contactName: "Ronald Slaats",
    contactTitle: "Group Managing Director",
    linkedinUrl: "https://linkedin.com/in/ronald-slaats",
    status: "verstuurd",
    batch: "2026-06-12",
    isNew: false,
    notes: "Bericht verzonden via LinkedIn op 13 juni.",
    message:
      "Hi Ronald, ik ben Levi van Legacy Scale Models. We lanceren twee premium merken: Universal Hobbies en Weise Toys. Met de indrukwekkende groei van ZWEQ is er een fit voor co-branded schaalmodellen — showrooms, klantloyaliteit, evenementen. Graag vroege partnervoorwaarden bespreken.",
  },
  {
    id: "4",
    company: "HH Agri / Van der Haeghe",
    country: "België",
    employees: 200,
    revenue: "€50M+",
    sector: "Agri Dealer",
    contactName: "Julien Vanderhaeghe",
    contactTitle: "COO",
    linkedinUrl: "https://linkedin.com/in/julien-vanderhaeghe",
    status: "opvolgen",
    batch: "2026-06-12",
    isNew: false,
    notes: "Heeft gereageerd, wil meer info over prijzen.",
    message:
      "Hi Julien, ik ben Levi van Legacy Scale Models. We breiden uit met twee premium merken — Universal Hobbies en Weise Toys. Als exclusief Fendt-distributeur in België zijn op maat gemaakte Fendt-schaalmodellen voor showrooms en klantengeschenken een natuurlijke fit.",
  },
  {
    id: "5",
    company: "Mechan International",
    country: "Nederland",
    employees: 300,
    revenue: "€100M+",
    sector: "Agri Importer",
    contactName: "Ronald Slaats",
    contactTitle: "CEO",
    linkedinUrl: "https://linkedin.com/in/ronald-slaats-mechan",
    status: "gewonnen",
    batch: "2026-06-12",
    isNew: false,
    notes: "Deal gesloten! 500 MF-modellen voor dealer gifting.",
    message:
      "Hi Ronald, ik ben Levi van Legacy Scale Models. We lanceren Universal Hobbies en Weise Toys. De snelle expansie van Mechan met Massey Ferguson door Europa maakt jullie een goede fit voor co-branded schaalmodellen. Vroege partnervoorwaarden beschikbaar.",
  },
  {
    id: "6",
    company: "Akershus Traktor A/S",
    country: "Noorwegen",
    employees: 200,
    revenue: "€20M",
    sector: "Agri Dealer",
    contactName: "Lars Eriksen",
    contactTitle: "General Manager",
    linkedinUrl: "https://linkedin.com/company/akershus-traktor",
    status: "nieuw",
    batch: "2026-06-13",
    isNew: true,
    notes: "",
    message:
      "Hi Lars, ik ben Levi van Legacy Scale Models. We breiden uit met Universal Hobbies en Weise Toys. Als toonaangevende Noorse agri-dealer zijn op maat gemaakte schaalmodellen krachtig voor showrooms en evenementen. We benaderen geselecteerde dealers vóór de lancering.",
  },
  {
    id: "7",
    company: "Royal De Boer Stalinrichtingen",
    country: "Nederland",
    employees: 115,
    revenue: "€30M",
    sector: "Dairy Equipment",
    contactName: "Peter de Boer",
    contactTitle: "Commercial Director",
    linkedinUrl: "https://linkedin.com/company/royal-de-boer",
    status: "nieuw",
    batch: "2026-06-13",
    isNew: true,
    notes: "",
    message:
      "Hi Peter, ik ben Levi van Legacy Scale Models — uitbreidend met Universal Hobbies en Weise Toys. Op maat gemaakte schaalmodellen van jullie apparatuur zijn een unieke toevoeging aan beurspresence en relatiegeschenken. Vroege partnervoorwaarden beschikbaar.",
  },
  {
    id: "8",
    company: "BayWa AG",
    country: "Duitsland",
    employees: 20000,
    revenue: "€17B",
    sector: "Agri Trading",
    contactName: "Thomas Müller",
    contactTitle: "Marketing Manager Agri Division",
    linkedinUrl: "https://linkedin.com/company/baywa-ag",
    status: "verloren",
    batch: "2026-06-13",
    isNew: true,
    notes: "Geen interesse op dit moment. Budget bevroren.",
    message:
      "Hi Thomas, ik ben Levi van Legacy Scale Models — uitbreidend met Universal Hobbies en Weise Toys. De schaal van BayWa maakt jullie een interessante partner voor co-branded schaalmodellen bij beurzen en loyaliteitsprogrammas.",
  },
  {
    id: "9",
    company: "Agromais",
    country: "Portugal",
    employees: 75,
    revenue: "€15M",
    sector: "Agri Dealer",
    contactName: "João Ferreira",
    contactTitle: "Commercial Director",
    linkedinUrl: "https://linkedin.com/company/agromais",
    status: "bekeken",
    batch: "2026-06-13",
    isNew: true,
    notes: "",
    message:
      "Hi João, ik ben Levi van Legacy Scale Models. We rebranden en lanceren Universal Hobbies en Weise Toys. Agromais is precies het type partner — schaalmodellen van de tractoren die jullie verkopen vallen op bij beurzen en versterken klantrelaties.",
  },
  {
    id: "10",
    company: "CLAAS KGaA",
    country: "Duitsland",
    employees: 12000,
    revenue: "€4.9B",
    sector: "Agri Manufacturer",
    contactName: "Anna Schmidt",
    contactTitle: "Brand & Marketing Manager",
    linkedinUrl: "https://linkedin.com/company/claas",
    status: "opvolgen",
    batch: "2026-06-13",
    isNew: true,
    notes: "Doorverwezen naar Brand Partnerships team.",
    message:
      "Hi Anna, ik ben Levi van Legacy Scale Models. We lanceren twee premium lijnen — Universal Hobbies en Weise Toys. CLAAS-schaalmodellen hebben enorme aantrekkingskracht voor beurzen, collector editions en dealergeschenken. Graag co-branded samenwerking verkennen.",
  },
];

export const SEED_LEADS: Lead[] = RAW_LEADS.map((l) => ({ ...l, score: fitScore(l) }));

export const BATCH_TEMPLATES = [
  {
    company: "Lemken GmbH & Co. KG",
    country: "Duitsland",
    employees: 1800,
    revenue: "€400M+",
    sector: "Agri Manufacturer",
    contactName: "Markus Lemken",
    contactTitle: "Head of Marketing",
  },
  {
    company: "Van der Sluis Agri",
    country: "Nederland",
    employees: 85,
    revenue: "€18M",
    sector: "Agri Dealer",
    contactName: "Jan van der Sluis",
    contactTitle: "Owner",
  },
  {
    company: "Grimme Landmaschinen",
    country: "Duitsland",
    employees: 3200,
    revenue: "€800M+",
    sector: "Agri Manufacturer",
    contactName: "Stefan Grimme",
    contactTitle: "Sales Director",
  },
  {
    company: "AgriTech Solutions BV",
    country: "Nederland",
    employees: 45,
    revenue: "€8M",
    sector: "Agri Importer",
    contactName: "Lisa de Vries",
    contactTitle: "Commercial Manager",
  },
  {
    company: "Nordic Farm Equipment",
    country: "Noorwegen",
    employees: 120,
    revenue: "€25M",
    sector: "Agri Dealer",
    contactName: "Erik Hansen",
    contactTitle: "CEO",
  },
];

export const EXPANDED_BATCH_POOL = [
  ...BATCH_TEMPLATES,
  {
    company: "Krone Ag",
    country: "Duitsland",
    employees: 2500,
    revenue: "€600M+",
    sector: "Agri Manufacturer",
    contactName: "Thomas Krone",
    contactTitle: "Marketing Director",
  },
  {
    company: "Bavaria Tractors GmbH",
    country: "Duitsland",
    employees: 450,
    revenue: "€90M",
    sector: "Agri Dealer",
    contactName: "Anna Weber",
    contactTitle: "Sales Manager",
  },
  {
    company: "Holland Agri Parts",
    country: "Nederland",
    employees: 65,
    revenue: "€12M",
    sector: "Agri Importer",
    contactName: "Pieter Jansen",
    contactTitle: "Owner",
  },
  {
    company: "Fendt België NV",
    country: "België",
    employees: 220,
    revenue: "€45M",
    sector: "Agri Dealer",
    contactName: "Sophie Maes",
    contactTitle: "Brand Manager",
  },
  {
    company: "GreenField Machinery",
    country: "Nederland",
    employees: 130,
    revenue: "€28M",
    sector: "Agri Machinery",
    contactName: "Mark de Boer",
    contactTitle: "Commercial Director",
  },
  {
    company: "Alpine Agri Systems",
    country: "Noorwegen",
    employees: 95,
    revenue: "€20M",
    sector: "Agri Importer",
    contactName: "Lars Nilsson",
    contactTitle: "CEO",
  },
  {
    company: "Rheinland Equipment Group",
    country: "Duitsland",
    employees: 890,
    revenue: "€180M",
    sector: "Agri Trading",
    contactName: "Klaus Müller",
    contactTitle: "Partnerships Lead",
  },
  {
    company: "Brabant Farm Services",
    country: "Nederland",
    employees: 40,
    revenue: "€7M",
    sector: "Agri Dealer",
    contactName: "Emma van Dijk",
    contactTitle: "Marketing Manager",
  },
  {
    company: "Iberian Agro Tech",
    country: "Portugal",
    employees: 175,
    revenue: "€32M",
    sector: "Agri Importer",
    contactName: "Carlos Mendes",
    contactTitle: "Sales Director",
  },
  {
    company: "Lowlands Machinery Co.",
    country: "Nederland",
    employees: 310,
    revenue: "€55M",
    sector: "Agri Manufacturer",
    contactName: "Sanne Bakker",
    contactTitle: "Head of Brand",
  },
];
